GET {{host}}/profiles/
Accept: application/json

###

GET {{host}}/count/profiles/1
Accept: application/json

###

POST {{host}}/profiles/
Accept: application/json
Content-Type: application/json

{
  "name": "nogti_zhe",
  "profile_type": 1,
  "ident": "4798404424"
}
###

PUT {{host}}/profiles/10
Accept: application/json
Content-Type: application/json

{
  "name": "nogti_zhe",
  "profile_type": 1,
  "ident": "4798404424"
}
###


DELETE {{host}}/profiles/11
Accept: application/json
Content-Type: application/json

###

GET {{host}}/vk/profiles?q=webart
Accept: application/json

###
POST {{host}}/vk/groups/
Accept: application/json
Content-Type: application/json

{
   "ident": 158405910
}

###
GET {{host}}/vk/groups/
Accept: application/json
Content-Type: application/json

###
DELETE {{host}}/vk/groups/158405910
Accept: application/json
Content-Type: application/json

###
GET {{host}}/vk/stat/groups/32963957
Accept: application/json
Content-Type: application/json

###
POST {{host}}/vk/stat/groups/32963957
Accept: application/json
Content-Type: application/json

### Категории
GET {{host}}/business/categories/sdf
Accept: application/json
Content-Type: application/json

###
POST {{host}}/business/categories/
Accept: application/json
Content-Type: application/json

{
  "name": "Sdf",
  "category_type": "sdf"
}

###
DELETE {{host}}/business/categories/5
Accept: application/json
Content-Type: application/json

### Клиенты
GET {{host}}/business/clients/
Accept: application/json
Content-Type: application/json

###
POST {{host}}/business/clients/
Accept: application/json
Content-Type: application/json

{
  "name": "Sdf",
  "phone": "sdf",
  "comment": "sdf",
  "type_client_id": "sdf"
}

###
PUT {{host}}/business/clients/1
Accept: application/json
Content-Type: application/json

{
  "name": "----",
  "phone": "sdf",
  "comment": "sdf"
}

###
DELETE {{host}}/business/clients/2
Accept: application/json
Content-Type: application/json

### Поступления
GET {{host}}/business/incomes/?dt_start=2020-09-17T14:29:39&dt_end=2021-09-17T14:29:39
Accept: application/json
Content-Type: application/json

###
POST {{host}}/business/incomes/
Accept: application/json
Content-Type: application/json

{
  "name": "Sdf",
  "price": 50,
  "category_id": 6,
  "client_id": 1
}

###
PUT {{host}}/business/incomes/1
Accept: application/json
Content-Type: application/json

{
  "name": "----",
  "price": 50,
  "category_id": 6,
  "client_id": 1
}

###
DELETE {{host}}/business/incomes/2
Accept: application/json
Content-Type: application/json