GET http://localhost:9999/v0/profiles/
Accept: application/json

###

POST http://localhost:9999/v0/profiles/
Accept: application/json
Content-Type: application/json

{
  "name": "sdfsdf",
  "profile_type": 1,
  "ident": "sdfsdf"
}
###

PUT http://localhost:9999/v0/profiles/10
Accept: application/json
Content-Type: application/json

{
  "name": "nogti_zhe",
  "profile_type": 1,
  "ident": "4798404424"
}
###


DELETE http://localhost:9999/v0/profiles/11
Accept: application/json
Content-Type: application/json

###

GET http://localhost:9999/v0/vk/profiles?q=webart
Accept: application/json

###
POST http://localhost:9999/v0/vk/groups/
Accept: application/json
Content-Type: application/json

{
   "ident": 158405910
}

###
GET http://localhost:9999/v0/vk/groups/
Accept: application/json
Content-Type: application/json

###
DELETE http://localhost:9999/v0/vk/groups/158405910
Accept: application/json
Content-Type: application/json

###
GET http://localhost:9999/v0/vk/stat/groups/32963957
Accept: application/json
Content-Type: application/json

###
POST http://localhost:9999/v0/vk/stat/groups/32963957
Accept: application/json
Content-Type: application/json