GET {{host}}/profiles/
Accept: application/json

###

GET {{host}}/count/profiles/4
Accept: application/json

###

POST {{host}}/profiles/
Accept: application/json
Content-Type: application/json

{
  "name": "nogti_zhe",
  "profile_type": 1,
  "ident": "4798404424"
}
###

PUT {{host}}/profiles/10
Accept: application/json
Content-Type: application/json

{
  "name": "nogti_zhe",
  "profile_type": 1,
  "ident": "4798404424"
}
###


DELETE {{host}}/profiles/11
Accept: application/json
Content-Type: application/json

###

GET {{host}}/vk/profiles?q=webart
Accept: application/json

###
POST {{host}}/vk/groups/
Accept: application/json
Content-Type: application/json

{
   "ident": 158405910
}

###
GET {{host}}/vk/groups/
Accept: application/json
Content-Type: application/json

###
DELETE {{host}}/vk/groups/158405910
Accept: application/json
Content-Type: application/json

###
GET {{host}}/vk/stat/groups/32963957
Accept: application/json
Content-Type: application/json

###
POST {{host}}/vk/stat/groups/32963957
Accept: application/json
Content-Type: application/json